services:
  # Application Service
  app:
    build: .
    container_name: portfolio-api
    restart: always
    # This loads the variables INTO the container at runtime
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GO_ENV=production
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
