// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: educations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEducation = `-- name: CreateEducation :one
insert into educations (
    profile_id, school, degree, field_of_study, gpa, start_date, graduation_date, is_present
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
) 
on conflict (profile_id, school, degree, start_date) do update set
    field_of_study = excluded.field_of_study,
    gpa = excluded.gpa,
    graduation_date = excluded.graduation_date,
    is_present = excluded.is_present
returning id, profile_id, school, degree, field_of_study, gpa, start_date, graduation_date, is_present
`

type CreateEducationParams struct {
	ProfileID      uuid.UUID
	School         string
	Degree         string
	FieldOfStudy   string
	Gpa            float64
	StartDate      pgtype.Date
	GraduationDate pgtype.Date
	IsPresent      bool
}

func (q *Queries) CreateEducation(ctx context.Context, arg CreateEducationParams) (Education, error) {
	row := q.db.QueryRow(ctx, createEducation,
		arg.ProfileID,
		arg.School,
		arg.Degree,
		arg.FieldOfStudy,
		arg.Gpa,
		arg.StartDate,
		arg.GraduationDate,
		arg.IsPresent,
	)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.School,
		&i.Degree,
		&i.FieldOfStudy,
		&i.Gpa,
		&i.StartDate,
		&i.GraduationDate,
		&i.IsPresent,
	)
	return i, err
}

const deleteEducation = `-- name: DeleteEducation :exec
delete from educations
where id = $1
`

func (q *Queries) DeleteEducation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEducation, id)
	return err
}

const getEducationByID = `-- name: GetEducationByID :one
select id, profile_id, school, degree, field_of_study, gpa, start_date, graduation_date, is_present from educations
where id = $1
`

func (q *Queries) GetEducationByID(ctx context.Context, id uuid.UUID) (Education, error) {
	row := q.db.QueryRow(ctx, getEducationByID, id)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.School,
		&i.Degree,
		&i.FieldOfStudy,
		&i.Gpa,
		&i.StartDate,
		&i.GraduationDate,
		&i.IsPresent,
	)
	return i, err
}

const getEducations = `-- name: GetEducations :many
select id, profile_id, school, degree, field_of_study, gpa, start_date, graduation_date, is_present from educations
where profile_id = $1
order by start_date desc
`

func (q *Queries) GetEducations(ctx context.Context, profileID uuid.UUID) ([]Education, error) {
	rows, err := q.db.Query(ctx, getEducations, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Education
	for rows.Next() {
		var i Education
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.School,
			&i.Degree,
			&i.FieldOfStudy,
			&i.Gpa,
			&i.StartDate,
			&i.GraduationDate,
			&i.IsPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEducation = `-- name: UpdateEducation :one
update educations
set
    school = COALESCE($2, school),
    degree = COALESCE($3, degree),
    field_of_study = COALESCE($4, field_of_study),
    gpa = COALESCE($5, gpa),
    start_date = COALESCE($6, start_date),
    graduation_date = COALESCE($7, graduation_date),
    is_present = COALESCE($8, is_present)
where id = $1
returning id, profile_id, school, degree, field_of_study, gpa, start_date, graduation_date, is_present
`

type UpdateEducationParams struct {
	ID             uuid.UUID
	School         string
	Degree         string
	FieldOfStudy   string
	Gpa            float64
	StartDate      pgtype.Date
	GraduationDate pgtype.Date
	IsPresent      bool
}

func (q *Queries) UpdateEducation(ctx context.Context, arg UpdateEducationParams) (Education, error) {
	row := q.db.QueryRow(ctx, updateEducation,
		arg.ID,
		arg.School,
		arg.Degree,
		arg.FieldOfStudy,
		arg.Gpa,
		arg.StartDate,
		arg.GraduationDate,
		arg.IsPresent,
	)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.School,
		&i.Degree,
		&i.FieldOfStudy,
		&i.Gpa,
		&i.StartDate,
		&i.GraduationDate,
		&i.IsPresent,
	)
	return i, err
}
