// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: experiences.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExperience = `-- name: CreateExperience :one
insert into experiences (
    profile_id, company, location, position, description, start_date, end_date, is_present
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
) 
on conflict (profile_id, company, position, start_date) do update set
    description = excluded.description,
    end_date = excluded.end_date,
    is_present = excluded.is_present
returning id, profile_id, company, position, description, location, start_date, end_date, is_present
`

type CreateExperienceParams struct {
	ProfileID   uuid.UUID
	Company     string
	Location    string
	Position    string
	Description []string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	IsPresent   bool
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.ProfileID,
		arg.Company,
		arg.Location,
		arg.Position,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.IsPresent,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Company,
		&i.Position,
		&i.Description,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.IsPresent,
	)
	return i, err
}

const deleteExperience = `-- name: DeleteExperience :exec
delete from experiences
where id = $1
`

func (q *Queries) DeleteExperience(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperience, id)
	return err
}

const getExperienceByID = `-- name: GetExperienceByID :one
select id, profile_id, company, position, description, location, start_date, end_date, is_present from experiences
where id = $1
`

func (q *Queries) GetExperienceByID(ctx context.Context, id uuid.UUID) (Experience, error) {
	row := q.db.QueryRow(ctx, getExperienceByID, id)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Company,
		&i.Position,
		&i.Description,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.IsPresent,
	)
	return i, err
}

const getExperiences = `-- name: GetExperiences :many
select id, profile_id, company, position, description, location, start_date, end_date, is_present from experiences
where profile_id = $1
order by start_date desc
`

func (q *Queries) GetExperiences(ctx context.Context, profileID uuid.UUID) ([]Experience, error) {
	rows, err := q.db.Query(ctx, getExperiences, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Company,
			&i.Position,
			&i.Description,
			&i.Location,
			&i.StartDate,
			&i.EndDate,
			&i.IsPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperience = `-- name: UpdateExperience :one
update experiences
set
    company = $2,
    position = $3,
    description = $4,
    start_date = $5,
    end_date = $6,
    is_present = $7,
    location = $8
where id = $1
returning id, profile_id, company, position, description, location, start_date, end_date, is_present
`

type UpdateExperienceParams struct {
	ID          uuid.UUID
	Company     string
	Position    string
	Description []string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	IsPresent   bool
	Location    string
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, updateExperience,
		arg.ID,
		arg.Company,
		arg.Position,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.IsPresent,
		arg.Location,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Company,
		&i.Position,
		&i.Description,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.IsPresent,
	)
	return i, err
}
