// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: experiences.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExperience = `-- name: CreateExperience :one
insert into experiences (
    profile_id, company, position, description, start_date, end_date
) values (
    $1, $2, $3, $4, $5, $6
) returning id, profile_id, company, position, description, start_date, end_date
`

type CreateExperienceParams struct {
	ProfileID   uuid.UUID
	Company     string
	Position    string
	Description string
	StartDate   time.Time
	EndDate     time.Time
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.ProfileID,
		arg.Company,
		arg.Position,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Company,
		&i.Position,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteExperience = `-- name: DeleteExperience :exec
delete from experiences
where id = $1
`

func (q *Queries) DeleteExperience(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperience, id)
	return err
}

const getExperiences = `-- name: GetExperiences :many
select id, profile_id, company, position, description, start_date, end_date from experiences
where profile_id = $1
order by start_date desc
`

func (q *Queries) GetExperiences(ctx context.Context, profileID uuid.UUID) ([]Experience, error) {
	rows, err := q.db.Query(ctx, getExperiences, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Company,
			&i.Position,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperience = `-- name: UpdateExperience :one
update experiences
set
    company = $2,
    position = $3,
    description = $4,
    start_date = $5,
    end_date = $6
where id = $1
returning id, profile_id, company, position, description, start_date, end_date
`

type UpdateExperienceParams struct {
	ID          uuid.UUID
	Company     string
	Position    string
	Description string
	StartDate   time.Time
	EndDate     time.Time
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, updateExperience,
		arg.ID,
		arg.Company,
		arg.Position,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Company,
		&i.Position,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
