// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: languages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLanguage = `-- name: CreateLanguage :one
insert into languages (
    profile_id, language, proficiency
) values (
    $1, $2, $3
) returning id, profile_id, language, proficiency
`

type CreateLanguageParams struct {
	ProfileID   uuid.UUID
	Language    string
	Proficiency ProficiencyLevel
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, arg.ProfileID, arg.Language, arg.Proficiency)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Language,
		&i.Proficiency,
	)
	return i, err
}

const deleteLanguage = `-- name: DeleteLanguage :exec
delete from languages
where id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLanguage, id)
	return err
}

const getLanguage = `-- name: GetLanguage :one
select id, profile_id, language, proficiency from languages
where id = $1 limit 1
`

func (q *Queries) GetLanguage(ctx context.Context, id uuid.UUID) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Language,
		&i.Proficiency,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
select id, profile_id, language, proficiency from languages
where profile_id = $1
order by language
`

func (q *Queries) ListLanguages(ctx context.Context, profileID uuid.UUID) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Language,
			&i.Proficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguage = `-- name: UpdateLanguage :one
update languages
set
    language = $2,
    proficiency = $3
where id = $1
returning id, profile_id, language, proficiency
`

type UpdateLanguageParams struct {
	ID          uuid.UUID
	Language    string
	Proficiency ProficiencyLevel
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, updateLanguage, arg.ID, arg.Language, arg.Proficiency)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Language,
		&i.Proficiency,
	)
	return i, err
}
