// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ProficiencyLevel string

const (
	ProficiencyLevelBasic        ProficiencyLevel = "basic"
	ProficiencyLevelIntermediate ProficiencyLevel = "intermediate"
	ProficiencyLevelAdvanced     ProficiencyLevel = "advanced"
	ProficiencyLevelProfessional ProficiencyLevel = "professional"
	ProficiencyLevelNative       ProficiencyLevel = "native"
)

func (e *ProficiencyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProficiencyLevel(s)
	case string:
		*e = ProficiencyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ProficiencyLevel: %T", src)
	}
	return nil
}

type NullProficiencyLevel struct {
	ProficiencyLevel ProficiencyLevel
	Valid            bool // Valid is true if ProficiencyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProficiencyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ProficiencyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProficiencyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProficiencyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProficiencyLevel), nil
}

type Education struct {
	ID             uuid.UUID
	ProfileID      uuid.UUID
	School         string
	Degree         string
	FieldOfStudy   string
	Gpa            float64
	StartDate      time.Time
	GraduationDate time.Time
}

type Experience struct {
	ID          uuid.UUID
	ProfileID   uuid.UUID
	Company     string
	Position    string
	Description []string
	StartDate   time.Time
	EndDate     time.Time
}

type Language struct {
	ID          uuid.UUID
	ProfileID   uuid.UUID
	Language    string
	Proficiency ProficiencyLevel
}

type Profile struct {
	ID      uuid.UUID
	Name    string
	About   string
	Address string
	Email   string
	Phone   string
}

type ProfileUrl struct {
	ID        uuid.UUID
	ProfileID uuid.UUID
	Label     string
	Url       string
}

type Project struct {
	ID            uuid.UUID
	ProfileID     uuid.UUID
	Title         string
	Description   string
	TechStacks    []string
	LiveDemoUrl   string
	GithubRepoUrl string
	IsLive        bool
	IsNda         bool
	IsFeatured    bool
	ImageUrl      string
	Company       string
	Period        string
	Location      string
}

type Skill struct {
	ID           uuid.UUID
	ProfileID    uuid.UUID
	Tools        []string
	Technologies []string
	HardSkills   []string
	SoftSkills   []string
}
