// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
insert into profiles (
    name, about, address, email, phone
) values (
    $1, $2, $3, $4, $5
) returning id, name, about, address, email, phone
`

type CreateProfileParams struct {
	Name    string
	About   string
	Address string
	Email   string
	Phone   string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.About,
		arg.Address,
		arg.Email,
		arg.Phone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.About,
		&i.Address,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
delete from profiles
where id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT
    p.id,
    p.name,
    p.about,
    p.address,
    p.email,
    p.phone,
    COALESCE(
        json_agg(
            json_build_object(
                'id', pu.id,
                'label', pu.label,
                'url', pu.url
            )
        ) FILTER (WHERE pu.id IS NOT NULL),
        '[]'
    ) AS urls
FROM profiles p
LEFT JOIN profile_urls pu ON pu.profile_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetProfileRow struct {
	ID      uuid.UUID
	Name    string
	About   string
	Address string
	Email   string
	Phone   string
	Urls    interface{}
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.About,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.Urls,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
update profiles
set
    name = COALESCE($2, name),
    about = COALESCE($3, about),
    address = COALESCE($4, address),
    email = COALESCE($5, email),
    phone = COALESCE($6, phone)
where id = $1
`

type UpdateProfileParams struct {
	ID      uuid.UUID
	Name    string
	About   string
	Address string
	Email   string
	Phone   string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.About,
		arg.Address,
		arg.Email,
		arg.Phone,
	)
	return err
}
