// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    name, title, about, address, email, phone
) values (
    $1, $2, $3, $4, $5, $6
) returning id, name, title, about, address, email, phone
`

type CreateProfileParams struct {
	Name    string
	Title   string
	About   string
	Address string
	Email   string
	Phone   string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.Title,
		arg.About,
		arg.Address,
		arg.Email,
		arg.Phone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.About,
		&i.Address,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
delete from profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT
    p.id,
    p.name,
    p.title,
    p.about,
    p.address,
    p.email,
    p.phone,

    urls.urls
FROM profiles p

LEFT JOIN LATERAL (
    SELECT COALESCE(jsonb_agg(u), '[]'::jsonb) AS urls
    FROM (
        SELECT
            id AS "ID",
            profile_id AS "ProfileID",
            label AS "Label",
            url AS "Url"
        FROM profile_urls
        WHERE profile_id = p.id
    ) u
) urls ON true

WHERE p.id = $1
`

type GetProfileRow struct {
	ID      uuid.UUID
	Name    string
	Title   string
	About   string
	Address string
	Email   string
	Phone   string
	Urls    interface{}
}

// URLS
func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.About,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.Urls,
	)
	return i, err
}

const getProfiles = `-- name: GetProfiles :many
SELECT
    p.id,
    p.name,
    p.title,
    p.about,
    p.address,
    p.email,
    p.phone,
    urls.urls
FROM profiles p
LEFT JOIN LATERAL (
    SELECT COALESCE(jsonb_agg(u), '[]'::jsonb) AS urls
    FROM (
        SELECT
            id AS "ID",
            profile_id AS "ProfileID",
            label AS "Label",
            url AS "Url"
        FROM profile_urls
        WHERE profile_id = p.id
    ) u
) urls ON true
ORDER BY p.name desc
`

type GetProfilesRow struct {
	ID      uuid.UUID
	Name    string
	Title   string
	About   string
	Address string
	Email   string
	Phone   string
	Urls    interface{}
}

func (q *Queries) GetProfiles(ctx context.Context) ([]GetProfilesRow, error) {
	rows, err := q.db.Query(ctx, getProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilesRow
	for rows.Next() {
		var i GetProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.About,
			&i.Address,
			&i.Email,
			&i.Phone,
			&i.Urls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET
    name = COALESCE($2, name),
    title = COALESCE($3, title),
    about = COALESCE($4, about),
    address = COALESCE($5, address),
    email = COALESCE($6, email),
    phone = COALESCE($7, phone)
WHERE id = $1
`

type UpdateProfileParams struct {
	ID      uuid.UUID
	Name    string
	Title   string
	About   string
	Address string
	Email   string
	Phone   string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.About,
		arg.Address,
		arg.Email,
		arg.Phone,
	)
	return err
}
