// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_urls.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProfileURL = `-- name: CreateProfileURL :one
insert into profile_urls (
    profile_id, label, url
) values (
    $1, $2, $3
) returning id, profile_id, label, url
`

type CreateProfileURLParams struct {
	ProfileID uuid.UUID
	Label     string
	Url       string
}

func (q *Queries) CreateProfileURL(ctx context.Context, arg CreateProfileURLParams) (ProfileUrl, error) {
	row := q.db.QueryRow(ctx, createProfileURL, arg.ProfileID, arg.Label, arg.Url)
	var i ProfileUrl
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Label,
		&i.Url,
	)
	return i, err
}

const deleteProfileURL = `-- name: DeleteProfileURL :exec
delete from profile_urls
where id = $1
`

func (q *Queries) DeleteProfileURL(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileURL, id)
	return err
}

const getProfileURL = `-- name: GetProfileURL :one
select id, profile_id, label, url from profile_urls
where id = $1 limit 1
`

func (q *Queries) GetProfileURL(ctx context.Context, id uuid.UUID) (ProfileUrl, error) {
	row := q.db.QueryRow(ctx, getProfileURL, id)
	var i ProfileUrl
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Label,
		&i.Url,
	)
	return i, err
}

const listProfileURLs = `-- name: ListProfileURLs :many
select id, profile_id, label, url from profile_urls
where profile_id = $1
order by label
`

func (q *Queries) ListProfileURLs(ctx context.Context, profileID uuid.UUID) ([]ProfileUrl, error) {
	rows, err := q.db.Query(ctx, listProfileURLs, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileUrl
	for rows.Next() {
		var i ProfileUrl
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Label,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileURL = `-- name: UpdateProfileURL :one
update profile_urls
set
    label = $2,
    url = $3
where id = $1
returning id, profile_id, label, url
`

type UpdateProfileURLParams struct {
	ID    uuid.UUID
	Label string
	Url   string
}

func (q *Queries) UpdateProfileURL(ctx context.Context, arg UpdateProfileURLParams) (ProfileUrl, error) {
	row := q.db.QueryRow(ctx, updateProfileURL, arg.ID, arg.Label, arg.Url)
	var i ProfileUrl
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Label,
		&i.Url,
	)
	return i, err
}
