// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
insert into projects (
    profile_id,
    title,
    description,
    tech_stacks,
    live_demo_url,
    github_repo_url,
    is_live,
    is_nda,
    is_featured,
    image_url,
    company,
    period,
    location
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
on conflict (profile_id, title)
do update set
    description = excluded.description,
    tech_stacks = excluded.tech_stacks,
    live_demo_url = excluded.live_demo_url,
    github_repo_url = excluded.github_repo_url,
    is_live = excluded.is_live,
    is_nda = excluded.is_nda,
    is_featured = excluded.is_featured,
    image_url = excluded.image_url,
    company = excluded.company,
    period = excluded.period,
    location = excluded.location
returning id, profile_id, title, description, tech_stacks, live_demo_url, github_repo_url, is_live, is_nda, is_featured, image_url, company, period, location
`

type CreateProjectParams struct {
	ProfileID     uuid.UUID
	Title         string
	Description   []string
	TechStacks    []string
	LiveDemoUrl   string
	GithubRepoUrl string
	IsLive        bool
	IsNda         bool
	IsFeatured    bool
	ImageUrl      string
	Company       string
	Period        string
	Location      string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProfileID,
		arg.Title,
		arg.Description,
		arg.TechStacks,
		arg.LiveDemoUrl,
		arg.GithubRepoUrl,
		arg.IsLive,
		arg.IsNda,
		arg.IsFeatured,
		arg.ImageUrl,
		arg.Company,
		arg.Period,
		arg.Location,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Title,
		&i.Description,
		&i.TechStacks,
		&i.LiveDemoUrl,
		&i.GithubRepoUrl,
		&i.IsLive,
		&i.IsNda,
		&i.IsFeatured,
		&i.ImageUrl,
		&i.Company,
		&i.Period,
		&i.Location,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
delete from projects
where id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
select id, profile_id, title, description, tech_stacks, live_demo_url, github_repo_url, is_live, is_nda, is_featured, image_url, company, period, location  from projects
where id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Title,
		&i.Description,
		&i.TechStacks,
		&i.LiveDemoUrl,
		&i.GithubRepoUrl,
		&i.IsLive,
		&i.IsNda,
		&i.IsFeatured,
		&i.ImageUrl,
		&i.Company,
		&i.Period,
		&i.Location,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
select id, profile_id, title, description, tech_stacks, live_demo_url, github_repo_url, is_live, is_nda, is_featured, image_url, company, period, location from projects
where profile_id = $1
order by period desc
`

func (q *Queries) GetProjects(ctx context.Context, profileID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjects, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Title,
			&i.Description,
			&i.TechStacks,
			&i.LiveDemoUrl,
			&i.GithubRepoUrl,
			&i.IsLive,
			&i.IsNda,
			&i.IsFeatured,
			&i.ImageUrl,
			&i.Company,
			&i.Period,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
update projects
set 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    tech_stacks = COALESCE($4, tech_stacks),
    live_demo_url = COALESCE($5, live_demo_url),
    github_repo_url = COALESCE($6, github_repo_url),
    is_live = COALESCE($7, is_live),
    is_nda = COALESCE($8, is_nda),
    is_featured = COALESCE($9, is_featured),
    image_url = COALESCE($10, image_url),
    company = COALESCE($11, company),
    period = COALESCE($12, period),
    location = COALESCE($13, location)
where id = $1
returning id, profile_id, title, description, tech_stacks, live_demo_url, github_repo_url, is_live, is_nda, is_featured, image_url, company, period, location
`

type UpdateProjectParams struct {
	ID            uuid.UUID
	Title         string
	Description   []string
	TechStacks    []string
	LiveDemoUrl   string
	GithubRepoUrl string
	IsLive        bool
	IsNda         bool
	IsFeatured    bool
	ImageUrl      string
	Company       string
	Period        string
	Location      string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TechStacks,
		arg.LiveDemoUrl,
		arg.GithubRepoUrl,
		arg.IsLive,
		arg.IsNda,
		arg.IsFeatured,
		arg.ImageUrl,
		arg.Company,
		arg.Period,
		arg.Location,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Title,
		&i.Description,
		&i.TechStacks,
		&i.LiveDemoUrl,
		&i.GithubRepoUrl,
		&i.IsLive,
		&i.IsNda,
		&i.IsFeatured,
		&i.ImageUrl,
		&i.Company,
		&i.Period,
		&i.Location,
	)
	return i, err
}
