// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
insert into skills (
    profile_id, tools, technologies, hard_skills, soft_skills
) values (
    $1, $2, $3, $4, $5
) 
on conflict (profile_id) do update set
    tools = excluded.tools,
    technologies = excluded.technologies,
    hard_skills = excluded.hard_skills,
    soft_skills = excluded.soft_skills
returning id, profile_id, tools, technologies, hard_skills, soft_skills
`

type CreateSkillParams struct {
	ProfileID    uuid.UUID
	Tools        []string
	Technologies []string
	HardSkills   []string
	SoftSkills   []string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ProfileID,
		arg.Tools,
		arg.Technologies,
		arg.HardSkills,
		arg.SoftSkills,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Tools,
		&i.Technologies,
		&i.HardSkills,
		&i.SoftSkills,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
delete from skills
where id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkillsByProfile = `-- name: GetSkillsByProfile :one
select id, profile_id, tools, technologies, hard_skills, soft_skills from skills
where profile_id = $1 limit 1
`

func (q *Queries) GetSkillsByProfile(ctx context.Context, profileID uuid.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillsByProfile, profileID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Tools,
		&i.Technologies,
		&i.HardSkills,
		&i.SoftSkills,
	)
	return i, err
}

const updateSkill = `-- name: UpdateSkill :one
update skills
set
    tools = $2,
    technologies = $3,
    hard_skills = $4,
    soft_skills = $5
where id = $1
returning id, profile_id, tools, technologies, hard_skills, soft_skills
`

type UpdateSkillParams struct {
	ID           uuid.UUID
	Tools        []string
	Technologies []string
	HardSkills   []string
	SoftSkills   []string
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Tools,
		arg.Technologies,
		arg.HardSkills,
		arg.SoftSkills,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Tools,
		&i.Technologies,
		&i.HardSkills,
		&i.SoftSkills,
	)
	return i, err
}
